package org.usfirst.frc.team178.robot.commands;

import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Relay.Value;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc.team178.robot.*;

public class Relays extends CammandBase{
	
	Relay lightRelay;
  
  	public Relays(){
  	}
  	
  	protected void execute(){
  		
  		lightRelay = new Relay(0);
  	
  	}
  	
  	protected boolean isFinished() {
  	
  		return false;
	
	}
	
	protected void end() {
	
	}
	
	protected void interrupted() {

	}


}

